name: Deploy to Hostinger

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Hostinger
        uses: burnett01/rsync-deployments@v6
        with:
          switches: -avz --delete
          path: build/ # atau sesuai folder hasil build di repo
          remote_path: public_html/build/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      - name: Run Laravel optimizations on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd public_html
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
